webtalk_init -webtalk_dir C:/TDD/lab03spi-g03/Ejercicios/Proyectos/Ejercicio2/vivado_project.sim/sim_1/behav/xsim/xsim.dir/tb_master_race_spi_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Oct  4 22:35:52 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "6dc1a4e8-e63b-4f51-a1ee-641d170a3c49" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "3213181789b34683a40c4a4d1327afb0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "70" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "660565100 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "20.67_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "11364_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2005087960 -regid "" -xml C:/TDD/lab03spi-g03/Ejercicios/Proyectos/Ejercicio2/vivado_project.sim/sim_1/behav/xsim/xsim.dir/tb_master_race_spi_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/TDD/lab03spi-g03/Ejercicios/Proyectos/Ejercicio2/vivado_project.sim/sim_1/behav/xsim/xsim.dir/tb_master_race_spi_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/TDD/lab03spi-g03/Ejercicios/Proyectos/Ejercicio2/vivado_project.sim/sim_1/behav/xsim/xsim.dir/tb_master_race_spi_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
