# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Documentos/GitHub/lab02-g03/lab03spi-g03/Ejercicios/Proyectos/Ejercicio2/vivado_project.cache/wt [current_project]
set_property parent.project_path D:/Documentos/GitHub/lab02-g03/lab03spi-g03/Ejercicios/Proyectos/Ejercicio2/vivado_project.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Documentos/GitHub/lab02-g03/lab03spi-g03/Ejercicios/Proyectos/Ejercicio2/vivado_project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  D:/Documentos/GitHub/lab02-g03/lab03spi-g03/Ejercicios/Ejercicio2/module_clk_divider_spi.sv
  D:/Documentos/GitHub/lab02-g03/lab03spi-g03/Ejercicios/Compartido/module_clock_divider.sv
  D:/Documentos/GitHub/lab02-g03/lab03spi-g03/Ejercicios/Ejercicio2/pkg_global.sv
  D:/Documentos/GitHub/lab02-g03/lab03spi-g03/Ejercicios/Ejercicio2/module_control_spi.sv
  D:/Documentos/GitHub/lab02-g03/lab03spi-g03/Ejercicios/Ejercicio2/module_memoria.sv
  D:/Documentos/GitHub/lab02-g03/lab03spi-g03/Ejercicios/Ejercicio2/module_mux_salida.sv
  D:/Documentos/GitHub/lab02-g03/lab03spi-g03/Ejercicios/Ejercicio2/module_mux_we.sv
  D:/Documentos/GitHub/lab02-g03/lab03spi-g03/Ejercicios/Ejercicio2/module_reg_control.sv
  D:/Documentos/GitHub/lab02-g03/lab03spi-g03/Ejercicios/Ejercicio2/module_reg_datos.sv
  D:/Documentos/GitHub/lab02-g03/lab03spi-g03/Ejercicios/Ejercicio2/module_reg_miso.sv
  D:/Documentos/GitHub/lab02-g03/lab03spi-g03/Ejercicios/Ejercicio2/module_reg_mosi.sv
  D:/Documentos/GitHub/lab02-g03/lab03spi-g03/Ejercicios/Ejercicio1/module_seg7_control.sv
  D:/Documentos/GitHub/lab02-g03/lab03spi-g03/Ejercicios/Ejercicio2/module_state_machine_spi.sv
  D:/Documentos/GitHub/lab02-g03/lab03spi-g03/Ejercicios/Ejercicio2/top_interface_spi.sv
  D:/Documentos/GitHub/lab02-g03/lab03spi-g03/Ejercicios/Ejercicio2/top_master_race_spi.sv
  D:/Documentos/GitHub/lab02-g03/lab03spi-g03/Ejercicios/Proyectos/Ejercicio2/vivado_project.srcs/sources_1/new/top_tactico.sv
}
read_ip -quiet D:/Documentos/GitHub/lab02-g03/lab03spi-g03/Ejercicios/scr/xci/WCLK/WCLK.xci
set_property used_in_implementation false [get_files -all d:/Documentos/GitHub/lab02-g03/lab03spi-g03/Ejercicios/scr/xci/WCLK/WCLK_board.xdc]
set_property used_in_implementation false [get_files -all d:/Documentos/GitHub/lab02-g03/lab03spi-g03/Ejercicios/scr/xci/WCLK/WCLK.xdc]
set_property used_in_implementation false [get_files -all d:/Documentos/GitHub/lab02-g03/lab03spi-g03/Ejercicios/scr/xci/WCLK/WCLK_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Documentos/GitHub/lab02-g03/lab03spi-g03/Ejercicios/Constraints/contraints_spi_master_race.xdc
set_property used_in_implementation false [get_files D:/Documentos/GitHub/lab02-g03/lab03spi-g03/Ejercicios/Constraints/contraints_spi_master_race.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top_tactico -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_tactico.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_tactico_utilization_synth.rpt -pb top_tactico_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
