# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/carlo/Andrey/TEC/Semestre_II_2022/Taller_Digitales/Laboratorios/Lab3/Repo/lab03spi-g03/Ejercicios/Constraints/contraints_spi_master_race.xdc

# IP: C:/Users/carlo/Andrey/TEC/Semestre_II_2022/Taller_Digitales/Laboratorios/Lab3/Repo/lab03spi-g03/Ejercicios/scr/xci/WCLK/WCLK.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WCLK || ORIG_REF_NAME==WCLK} -quiet] -quiet
